name: "Unit Tests"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run tests challenge-1
        run: go test -v ./challenge-1
      - name: Run tests challenge-2
        run: go test -v ./challenge-2
